# Generated by Django 3.2.4 on 2021-07-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
